"""Raw TipTap payload keys."""

TYPE = "type"
ATTRS = "attrs"
CONTENT = "content"
TEXT = "text"
MARKS = "marks"
ID = "id"
TIPTAP_ID = "tiptapId"
SHARED_ID = "sharedId"
SHARED = "shared"
PLACE = "place"
LEVEL = "level"
CHECKED = "checked"
STATUS = "status"
TASK_CANONICAL_ID = "taskCanonicalId"
