"""TipTap node kinds."""

DOC = "doc"
TEXT = "text"
PARAGRAPH = "paragraph"
HEADING = "heading"
TASK_ITEM = "taskItem"
TASK_LIST = "taskList"
LIST_ITEM = "listItem"
BULLET_LIST = "bulletList"
ORDERED_LIST = "orderedList"
BLOCKQUOTE = "blockquote"
CODE_BLOCK = "codeBlock"
TABLE_CELL = "tableCell"
